### ISSUE TITLE
Error in Spigot 1.14.3 (ClassNotFound)

### ISSUE THREAD

**Issue by Doc94** [InventivetalentDev/GlowAPI#21] opened 2019-07-08 19:10 UTC
## What steps will reproduce the problem?  
1. Run plugin in 1.14.3

## What were you expecting to happen? What happened instead?  
Return a missing class `IntHashMap`

## What Spigot version are you using? *Type /version*  
`This server is running CraftBukkit version git-Spigot-d05d3c1-087a2cf (MC: 1.14.3) (Implementing API version 1.14.3-R0.1-SNAPSHOT)`

**Comment by InventivetalentDev** [comment] 2019-07-12 17:34
Should be fixed by https://github.com/InventivetalentDev/GlowAPI/commit/682bf9b669daa83b1d65438163bf8fdb49f1d489

**Comment by Midnight9746** [comment] 2019-08-25 18:51
@InventivetalentDev

On 1.14.4, this happens:

"25.08 18:02:53 [Server] Server thread/WARN Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap"

And glowing would 'work' but it will keep the entity glowing and won't use color besides white.

**Comment by InventivetalentDev** [comment] 2019-08-25 18:55
Full stacktrace, please.

**Comment by Midnight9746** [comment] 2019-08-25 19:04
https://pastebin.com/NVmdNX8g

**Comment by Midnight9746** [comment] 2019-09-06 20:20
@iventivetalentDev

Here's more of the stacktrace, https://pastebin.com/NfVDnc8e

**Comment by Midnight9746** [comment] 2019-09-06 20:20
@InventivetalentDev
Here's more of the stacktrace, https://pastebin.com/NfVDnc8e

**Comment by Skeagle137** [comment] 2020-03-08 02:05
Still happening in 1.15.2

**Comment by InventivetalentDev** [comment] 2020-05-07 07:50
Should be fixed #27

**Closed by InventivetalentDev** 2020-05-07 07:50 UTC
Labels: wontfix

**Comment by Midnight9746** [comment] 2020-05-07 11:20
> Should be fixed #27

It's fixed for me - I used a dev build a few months ago. Thanks!
